// exmxc | Single Page Audit API — Stable Working Build (Axios + Cheerio + Resend)
import axios from "axios";
import * as cheerio from "cheerio"; // ✅ ESM-safe import

export default async function handler(req, res) {
  try {
    const { url, email } = req.body || {};
    if (!url) return res.status(400).json({ error: "Missing URL" });

    // Fetch and parse HTML
    const { data } = await axios.get(url, { timeout: 15000 });
    const $ = cheerio.load(data);

    // Extract key metadata
    const canonical = $('link[rel="canonical"]').attr("href") || null;
    const description = $('meta[name="description"]').attr("content") || null;
    const schemaCount = $('script[type="application/ld+json"]').length;
    const title = $("title").text() || null;

    // Simple entity score heuristic
    let entityScore = 0;
    if (canonical) entityScore += 30;
    if (description) entityScore += 30;
    if (schemaCount > 0) entityScore += 40;

    const result = {
      url,
      title,
      canonical,
      description,
      schemaCount,
      entityScore,
      timestamp: new Date().toISOString()
    };

    // Optional email via Resend
    if (email && process.env.RESEND_API_KEY) {
      const { Resend } = await import("resend");
      const resend = new Resend(process.env.RESEND_API_KEY);

      await resend.emails.send({
        from: "exmxc Audit <audit@exmxc.ai>",
        to: email,
        subject: `Audit Report: ${url}`,
        html: `
          <h3>exmxc.ai Audit Result</h3>
          <p><strong>URL:</strong> ${url}</p>
          <p><strong>Canonical:</strong> ${canonical || "None"}</p>
          <p><strong>Description:</strong> ${description || "None"}</p>
          <p><strong>Schema Count:</strong> ${schemaCount}</p>
          <p><strong>Entity Score:</strong> ${entityScore}</p>
          <small>Generated by exmxc Audit Baseline v1.0</small>
        `
      });
    }

    return res.status(200).json(result);
  } catch (err) {
    console.error("Audit error:", err.message);
    return res.status(500).json({ error: "Failed to fetch or parse page" });
  }
}
